=== OscarToorres/full-course-dam/DAM-1/Lenguaje de Marcas/2º Evaluacion/Tema 4/Ejercicios/Actividad 2/Ejercicio 1/Ejercicio_1_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="eventos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="evento"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="evento">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="mes" type="xs:string"/>
        <xs:element name="lugar" type="xs:string"/>
        <xs:element name="duracion" type="xs:string"/>
        <xs:element ref="organizador"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="organizador">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre_o" type="xs:string"/>
        <xs:element name="profesion" type="xs:string"/>
        <xs:element name="fecha_nac" type="xs:string"/>
        <xs:element ref="ciudad"/>
        <xs:element ref="telefono"/>
        <xs:element name="email" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ciudad">
    <xs:complexType mixed="true">
      <xs:attribute name="cp" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="telefono">
    <xs:complexType>
      <xs:attribute name="n" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== OscarToorres/full-course-dam/DAM-1/Lenguaje de Marcas/2º Evaluacion/Tema 4/Ejercicios/Actividad 2/Ejercicio 1/Ejercicio_1_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio_1_Schema.xsd">
    <evento>
        <nombre>Diverciencia</nombre>
        <mes>mayo</mes>
        <lugar>Algeciras</lugar>
        <duracion>1 semana</duracion>
        <organizador>
            <nombre_o>Juan manuel C.</nombre_o>
            <profesion>matematico</profesion>
            <fecha_nac>07/05/1960</fecha_nac>
            <ciudad cp="29700">Malaga</ciudad>
            <telefono n="666666666"/>
            <email>lm@prueba.com</email>
        </organizador>
    </evento>
</eventos>
