=== OscarToorres/full-course-dam/DAM-1/Lenguaje de Marcas/2º Evaluacion/Tema 4/Ejercicios/Actividad 2/Ejercicio 2/Ejercicio_2_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="agenda">
        <xs:complexType> 
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="contacto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre_apellidos" type="xs:string"/>
                            <xs:element minOccurs="0" maxOccurs="2" name="telefono" type="xs:unsignedInt" />
                            <xs:element name="edad" type="xs:unsignedByte"/>
                            <xs:element minOccurs="1" maxOccurs="3" name="email" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OscarToorres/full-course-dam/DAM-1/Lenguaje de Marcas/2º Evaluacion/Tema 4/Ejercicios/Actividad 2/Ejercicio 2/Ejercicio_2_XML.xml
<?xml version="1.0" encoding="utf-8"?>
<agenda xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Ejercicio_2_Schema.xsd">
    <contacto>
        <nombre_apellidos>Oscar Torres Rodríguez</nombre_apellidos>
        <telefono>666666666</telefono>
        <edad>19</edad>
        <email>estoesunejemplo@gmail.com</email>
    </contacto>
    <contacto>
        <nombre_apellidos>Ramon Arturo Rodríguez</nombre_apellidos>
        <telefono>666667666</telefono>
        <telefono>666667667</telefono>
        <edad>23</edad>
        <email>estoesunejemplo1@gmail.com</email>
        <email>estoesunejemplo2@gmail.com</email>
        <email>estoesunejemplo3@gmail.com</email>
    </contacto>
    <contacto>
        <nombre_apellidos>Manuel Torres Gonzalez</nombre_apellidos>
        <edad>40</edad>
        <email>estoesunejemplo4@gmail.com</email>
    </contacto>
</agenda>
